import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, Router } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen'; // This file will be generated by TanStack Router CLI

import './index.css';

// Create a client
const queryClient = new QueryClient();

// Create the router using your route tree
const router = new Router({ routeTree, basepath: '/'});

// Register your router for maximum type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
